graph TD
  content-equations-gibbs-free-energy["content-equations-gibbs-free-energy"] -->|scientist| josiah-willard-gibbs["josiah-willard-gibbs"]
  content-people-josiah-willard-gibbs["content-people-josiah-willard-gibbs"] -->|related| content-physical-thermodynamics["content-physical-thermodynamics"]
  content-physical-thermodynamics["content-physical-thermodynamics"] -->|links_to| content-equations-gibbs-free-energy["content-equations-gibbs-free-energy"]
  content-physical-thermodynamics["content-physical-thermodynamics"] -->|prerequisite| content-equations-gibbs-free-energy["content-equations-gibbs-free-energy"]
  content-physical-thermodynamics["content-physical-thermodynamics"] -->|links_to| content-people-josiah-willard-gibbs["content-people-josiah-willard-gibbs"]
  content-physical-thermodynamics["content-physical-thermodynamics"] -->|related| content-people-josiah-willard-gibbs["content-people-josiah-willard-gibbs"]
  content-physical-thermodynamics["content-physical-thermodynamics"] -->|equation| gibbs-free-energy["gibbs-free-energy"]
